namespace WTVRSettingsAssistant;

internal static partial class AppText
{
    private static Dictionary<string, string> UkrainianTranslations() => new()
    {
        ["Nav.Home"] = "Головна",
        ["Nav.Profiles"] = "Профілі",
        ["Nav.Neck"] = "Помічник огляду",
        ["Nav.Keybind"] = "Помічник клавіш",
        ["Nav.VTrim"] = "Помічник VTrim",
        ["Nav.Options"] = "Налаштування програми",
        ["Nav.Info"] = "Інформація",
        ["Nav.Updates"] = "Оновити програму",
        ["Nav.GameUpdates"] = "Оновлення гри",

        ["Home.ModeHeading"] = "РЕЖИМ ГРИ",
        ["Home.Monitor"] = "МОНІТОР",
        ["Home.VR"] = "VR",
        ["Home.Launch"] = "ЗАПУСТИТИ ГРУ",
        ["Home.LaunchAction"] = "ЗАПУСК",
        ["Home.UpdateAction"] = "ОНОВИТИ",
        ["Home.RunningAction"] = "ЗАПУЩЕНО",
        ["Home.LiveServer"] = "LIVE",
        ["Home.TestServer"] = "TEST",
        ["Home.Version"] = "Версія {0}",
        ["Home.Support"] = "Купити мені пиво!",
        ["Home.Discord"] = "DISCORD",
        ["Home.YouTube"] = "YOUTUBE",

        ["Profiles.Heading"] = "ПРОФІЛІ",
        ["Profiles.Tip"] = "Оберіть папку War Thunder один раз; файли config і launcher буде знайдено автоматично.",
        ["Profiles.FolderTitle"] = "ПАПКА WAR THUNDER",
        ["Profiles.FolderDesc"] = "Знайдіть папку встановлення War Thunder.",
        ["Profiles.MonitorTitle"] = "ПРОФІЛЬ МОНІТОРА",
        ["Profiles.MonitorDesc"] = "Ваші налаштування War Thunder для монітора.",
        ["Profiles.VrPresets"] = "ПРЕСЕТИ VR",
        ["Profiles.CustomVrProfile"] = "ВЛАСНИЙ ПРОФІЛЬ VR",
        ["Profiles.CustomVrDesc"] = "Ваші налаштування War Thunder для VR.",
        ["Profiles.Controls"] = "ПРОФІЛІ КЕРУВАННЯ",
        ["Profiles.ControlsDesc"] = "Оберіть власні налаштування керування для різних пресетів (необов'язково).",
        ["Profiles.Recommended"] = "РЕКОМЕНДОВАНІ НАЛАШТУВАННЯ",
        ["Profiles.Browse"] = "ОБРАТИ",
        ["Profiles.Capture"] = "ЗБЕРЕГТИ НАЛАШТУВАННЯ",
        ["Profiles.Remove"] = "ВИДАЛИТИ",
        ["Profiles.Low"] = "НИЗЬКІ",
        ["Profiles.Medium"] = "СЕРЕДНІ",
        ["Profiles.High"] = "ВИСОКІ",
        ["Profiles.Off"] = "ВИМК.",

        ["Options.Title"] = "ПАРАМЕТРИ ЗАПУСКУ ТА ДРАЙВЕРІВ",
        ["Options.Language"] = "Мова",
        ["Options.Theme"] = "Візуальна тема",
        ["Options.Minimize"] = "Кнопка закриття згортає програму в системний трей",
        ["Options.Startup"] = "Запускати разом із Windows, згорнутою в трей",
        ["Options.TrayHelp"] = "Двічі клацніть піктограму в треї, щоб повернути вікно.",
        ["Options.VJoyHelp"] = "Обслуговування vJoy. Видалення прибирає лише віртуальний драйвер джойстика; профілі та файли користувача залишаються.",
        ["Options.UninstallVJoy"] = "ВИДАЛИТИ vJoy",
        ["Options.Save"] = "ЗБЕРЕГТИ",
        ["Options.Cancel"] = "СКАСУВАТИ",

        ["Assistant.EnableKeybind"] = "Увімкнути Помічник клавіш",
        ["Assistant.AdvancedSwitch"] = "Розширені прив'язки перемикачів",
        ["Assistant.BindInput"] = "ПРИВ'ЯЗАТИ ВВІД",
        ["Assistant.Back"] = "НАЗАД",
        ["Assistant.EnableNeck"] = "Увімкнути Помічник огляду",
        ["Assistant.Enable"] = "Увімкнути",
        ["Assistant.EnableUpDown"] = "Увімкнути вгору/вниз",
        ["Assistant.Advanced"] = "РОЗШИРЕНИЙ",
        ["Assistant.Simple"] = "ПРОСТИЙ",
        ["Assistant.Hold"] = "УТРИМАННЯ",
        ["Assistant.Toggle"] = "ПЕРЕМИКАЧ",
        ["Assistant.Clear"] = "ОЧИСТИТИ",
        ["Assistant.Active"] = "● АКТИВНО",
        ["Assistant.Off"] = "○ ВИМК.",
        ["Assistant.Yaw"] = "ЛІВОРУЧ / ПРАВОРУЧ (YAW)",
        ["Assistant.Pitch"] = "ВГОРУ / ВНИЗ (PITCH)",

        ["Neck.TransitionSpeed"] = "ПЕРЕХІД КАМЕРИ",
        ["Neck.TransitionHelp"] = "Нижче = повільніше й плавніше  •  Вище = швидша реакція.",
        ["Neck.RestoreDefaults"] = "ВІДНОВИТИ ТИПОВІ",
        ["Neck.Card.Horizontal"] = "Горизонтально",
        ["Neck.Card.Vertical"] = "Вертикально",
        ["Neck.Card.Activation"] = "Активація",
        ["Neck.Card.Release"] = "Відпускання",
        ["Neck.Card.NaturalMotion"] = "Природний рух",
        ["Neck.Card.MaximumView"] = "Максимальний огляд",
        ["Neck.Card.Softness"] = "Плавність",
        ["Neck.RuntimeSupport"] = "Автоматично працює зі SteamVR, OpenXR та VDXR.",

        ["Keybind.EnabledStatus"] = "Увімкнено. Команди клавіатури, миші та HOTAS активні.",
        ["Keybind.OffStatus"] = "Помічник клавіш вимкнено.",
        ["Switch.AdvancedBindings"] = "Розширені прив'язки перемикачів",
        ["Switch.AddSwitch"] = "Додати перемикач",
        ["Switch.Options"] = "Розширені параметри перемикачів",
        ["Switch.StatusColumn"] = "Стан",

        ["Binding.Title"] = "Прив'язати клавіатуру, мишу або HOTAS",
        ["Binding.Prompt"] = "Натисніть {0} або комбінацію",
        ["Binding.Assign"] = "Зберегти",
        ["Binding.Save"] = "Зберегти",
        ["Binding.TryAgain"] = "Спробувати ще",
        ["Binding.Cancel"] = "Скасувати",

        ["Common.On"] = "УВІМК.",
        ["Common.Off"] = "ВИМК.",
        ["Common.Save"] = "Зберегти",
        ["Common.Cancel"] = "Скасувати",

        ["Update.Title"] = "Оновлення програми",
        ["Update.Latest"] = "Ви використовуєте останню версію ({0}).",
        ["Info.Title"] = "WAR THUNDER VR ASSISTANT",
        ["Info.Purpose"] = "Програма Windows для перемикання профілів монітора й VR у War Thunder, керування профілями керування та покращення VR-огляду.",
        ["Info.HowTitle"] = "Як користуватися",
        ["Info.OpenSource"] = "Безкоштовне програмне забезпечення спільноти з відкритим кодом. Цей неофіційний інструмент не пов'язаний із Gaijin Entertainment.",
    };
}
