namespace WTVRSettingsAssistant;

internal static partial class AppText
{
    private static void AddRelease21LateTranslations()
    {
        foreach ((string code, string raw) in Release21LatePacks)
        {
            if (!SupplementalTexts.TryGetValue(code, out Dictionary<string, string>? target))
            {
                target = new Dictionary<string, string>(StringComparer.Ordinal);
                SupplementalTexts[code] = target;
            }
            foreach ((string key, string value) in ParseRelease21Pack(raw))
                target[key] = value;
        }
    }

    private static readonly Dictionary<string, string> Release21LatePacks = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = """
Switch.SequenceTitle=Action sequence
Switch.SequenceKey=Key
Switch.SequencePressCount=Press count (1–20)
Switch.SequenceDelay=Delay after press (ms, 0–5000)
Switch.SequenceAddKey=Add key
Switch.SequenceRemove=Remove
Switch.SequenceMoveUp=Move up
Switch.SequenceMoveDown=Move down
Switch.SequenceCaptureKey=Capture key
Switch.SequenceValidation=Choose a key, 1–20 presses, and an interval of 0–5000 ms for each row.
Switch.GestureTitle=Record advanced gesture
Switch.GestureRecord=Record
Switch.GestureStop=Stop
Switch.GestureUse=Use gesture
Switch.GestureDisconnected=Device disconnected. Record again.
Switch.GestureLine={0} ms | buttons 0x{1:X8}
Switch.SequenceKeyboardOnly=This row uses a keyboard sequence. Add a separate mouse row.
Switch.GestureNeedsSequence=Assign an Action Sequence to the recorded gesture before saving.
Switch.LegacyFlapsRemoved=Legacy automated flap logic was removed. Configure a normal action sequence, then enable the switch.
Switch.VJoyOutputTitle=vJoy output
Game.VerifyBranchFailed=WT Assistant could not verify the required {0} build from Gaijin.\n\nThe game will not launch against an unverified branch. Check your internet connection and try again.
Game.VersionCheckTitle=War Thunder version check
Game.BranchUpdateIncomplete=The official launcher finished, but the installed build ({0}) still does not exactly match the selected {1} build ({2}).\n\nWT Assistant will not launch the wrong branch.
Game.BranchUpdateTitle=Branch update not complete
Game.UpdateInProgress=A game update is already in progress.
Game.UpdateDialogTitle=Update War Thunder
Game.UpdateButton=UPDATE GAME
Game.InstallationNotFound=War Thunder installation not found.
Game.UpdateInfo={0}  •  Installed {1}  •  Server {2}
Game.UpdateVersionVerifyFailed=The selected server version could not be verified. Check your connection and try again.
Game.UpdateAlreadyInstalled=The selected server version is already installed.
Game.UpdateOfficialLauncher=Updating through the official launcher. It will close automatically when the update completes.
Game.UpdateComplete=Update complete: {0}.
Game.UpdateUnconfirmed=The launcher closed, but the selected version could not yet be confirmed.
Game.UpdateLauncherFailed=The official launcher update did not complete.
Warning.CloseLauncherBeforeServer=Close the War Thunder launcher before changing the Live/Test server.
""",
        ["bg"] = """
Switch.SequenceTitle=Последователност от действия
Switch.SequenceKey=Клавиш
Switch.SequencePressCount=Брой натискания (1–20)
Switch.SequenceDelay=Закъснение след натискане (ms, 0–5000)
Switch.SequenceAddKey=Добави клавиш
Switch.SequenceRemove=Премахни
Switch.SequenceMoveUp=Премести нагоре
Switch.SequenceMoveDown=Премести надолу
Switch.SequenceCaptureKey=Засечи клавиш
Switch.SequenceValidation=Избери клавиш, 1–20 натискания и интервал 0–5000 ms за всеки ред.
Switch.GestureTitle=Запис на разширен жест
Switch.GestureRecord=Запис
Switch.GestureStop=Спри
Switch.GestureUse=Използвай жеста
Switch.GestureDisconnected=Устройството е разкачено. Запиши отново.
Switch.GestureLine={0} ms | бутони 0x{1:X8}
Switch.SequenceKeyboardOnly=Този ред използва клавиатурна последователност. Добави отделен ред за мишка.
Switch.GestureNeedsSequence=Задай Action Sequence на записания жест преди запазване.
Switch.LegacyFlapsRemoved=Старата автоматична логика за flaps е премахната. Настрой нормална последователност от действия и включи switch-а.
Switch.VJoyOutputTitle=vJoy изход
Game.VerifyBranchFailed=WT Assistant не можа да провери необходимия {0} build от Gaijin.\n\nИграта няма да стартира към непроверен branch. Провери интернет връзката и опитай отново.
Game.VersionCheckTitle=Проверка на версията на War Thunder
Game.BranchUpdateIncomplete=Официалният launcher приключи, но инсталираният build ({0}) все още не съвпада точно с избрания {1} build ({2}).\n\nWT Assistant няма да стартира грешния branch.
Game.BranchUpdateTitle=Обновяването на branch-а не е завършило
Game.UpdateInProgress=Вече се извършва обновяване на играта.
Game.UpdateDialogTitle=Обновяване на War Thunder
Game.UpdateButton=ОБНОВИ ИГРАТА
Game.InstallationNotFound=Инсталацията на War Thunder не е намерена.
Game.UpdateInfo={0}  •  Инсталирана {1}  •  Сървър {2}
Game.UpdateVersionVerifyFailed=Версията на избрания сървър не можа да бъде проверена. Провери връзката и опитай отново.
Game.UpdateAlreadyInstalled=Версията на избрания сървър вече е инсталирана.
Game.UpdateOfficialLauncher=Обновяване чрез официалния launcher. Той ще се затвори автоматично след приключване.
Game.UpdateComplete=Обновяването приключи: {0}.
Game.UpdateUnconfirmed=Launcher-ът се затвори, но избраната версия все още не може да бъде потвърдена.
Game.UpdateLauncherFailed=Обновяването чрез официалния launcher не завърши.
Warning.CloseLauncherBeforeServer=Затвори War Thunder launcher-а преди смяна на Live/Test сървъра.
""",
        ["es"] = """
Switch.SequenceTitle=Secuencia de acciones
Switch.SequenceKey=Tecla
Switch.SequencePressCount=Número de pulsaciones (1–20)
Switch.SequenceDelay=Retraso tras pulsar (ms, 0–5000)
Switch.SequenceAddKey=Añadir tecla
Switch.SequenceRemove=Eliminar
Switch.SequenceMoveUp=Subir
Switch.SequenceMoveDown=Bajar
Switch.SequenceCaptureKey=Capturar tecla
Switch.SequenceValidation=Elige una tecla, 1–20 pulsaciones y un intervalo de 0–5000 ms para cada fila.
Switch.GestureTitle=Grabar gesto avanzado
Switch.GestureRecord=Grabar
Switch.GestureStop=Detener
Switch.GestureUse=Usar gesto
Switch.GestureDisconnected=Dispositivo desconectado. Graba de nuevo.
Switch.GestureLine={0} ms | botones 0x{1:X8}
Switch.SequenceKeyboardOnly=Esta fila usa una secuencia de teclado. Añade una fila independiente para el ratón.
Switch.GestureNeedsSequence=Asigna una secuencia de acciones al gesto grabado antes de guardar.
Switch.LegacyFlapsRemoved=Se eliminó la antigua lógica automática de flaps. Configura una secuencia de acciones normal y activa el interruptor.
Switch.VJoyOutputTitle=Salida vJoy
Game.VerifyBranchFailed=WT Assistant no pudo verificar la compilación {0} requerida de Gaijin.\n\nEl juego no se iniciará con una rama sin verificar. Comprueba tu conexión e inténtalo de nuevo.
Game.VersionCheckTitle=Comprobación de versión de War Thunder
Game.BranchUpdateIncomplete=El lanzador oficial terminó, pero la compilación instalada ({0}) aún no coincide exactamente con la compilación {1} seleccionada ({2}).\n\nWT Assistant no iniciará la rama incorrecta.
Game.BranchUpdateTitle=Actualización de rama incompleta
Game.UpdateInProgress=Ya hay una actualización del juego en curso.
Game.UpdateDialogTitle=Actualizar War Thunder
Game.UpdateButton=ACTUALIZAR JUEGO
Game.InstallationNotFound=No se encontró la instalación de War Thunder.
Game.UpdateInfo={0}  •  Instalada {1}  •  Servidor {2}
Game.UpdateVersionVerifyFailed=No se pudo verificar la versión del servidor seleccionado. Comprueba la conexión e inténtalo de nuevo.
Game.UpdateAlreadyInstalled=La versión del servidor seleccionado ya está instalada.
Game.UpdateOfficialLauncher=Actualizando mediante el lanzador oficial. Se cerrará automáticamente al terminar.
Game.UpdateComplete=Actualización completada: {0}.
Game.UpdateUnconfirmed=El lanzador se cerró, pero aún no se pudo confirmar la versión seleccionada.
Game.UpdateLauncherFailed=La actualización del lanzador oficial no se completó.
Warning.CloseLauncherBeforeServer=Cierra el lanzador de War Thunder antes de cambiar el servidor Live/Test.
""",
        ["de"] = """
Switch.SequenceTitle=Aktionssequenz
Switch.SequenceKey=Taste
Switch.SequencePressCount=Anzahl der Tastendrücke (1–20)
Switch.SequenceDelay=Verzögerung nach Tastendruck (ms, 0–5000)
Switch.SequenceAddKey=Taste hinzufügen
Switch.SequenceRemove=Entfernen
Switch.SequenceMoveUp=Nach oben
Switch.SequenceMoveDown=Nach unten
Switch.SequenceCaptureKey=Taste erfassen
Switch.SequenceValidation=Wähle für jede Zeile eine Taste, 1–20 Tastendrücke und ein Intervall von 0–5000 ms.
Switch.GestureTitle=Erweiterte Geste aufzeichnen
Switch.GestureRecord=Aufzeichnen
Switch.GestureStop=Stopp
Switch.GestureUse=Geste verwenden
Switch.GestureDisconnected=Gerät getrennt. Erneut aufzeichnen.
Switch.GestureLine={0} ms | Tasten 0x{1:X8}
Switch.SequenceKeyboardOnly=Diese Zeile verwendet eine Tastatursequenz. Füge eine separate Mauszeile hinzu.
Switch.GestureNeedsSequence=Weise der aufgezeichneten Geste vor dem Speichern eine Aktionssequenz zu.
Switch.LegacyFlapsRemoved=Die alte automatische Klappenlogik wurde entfernt. Konfiguriere eine normale Aktionssequenz und aktiviere dann den Schalter.
Switch.VJoyOutputTitle=vJoy-Ausgabe
Game.VerifyBranchFailed=WT Assistant konnte den erforderlichen {0}-Build von Gaijin nicht prüfen.\n\nDas Spiel startet nicht mit einem ungeprüften Branch. Prüfe die Internetverbindung und versuche es erneut.
Game.VersionCheckTitle=War-Thunder-Versionsprüfung
Game.BranchUpdateIncomplete=Der offizielle Launcher wurde beendet, aber der installierte Build ({0}) stimmt noch nicht exakt mit dem gewählten {1}-Build ({2}) überein.\n\nWT Assistant startet nicht den falschen Branch.
Game.BranchUpdateTitle=Branch-Update nicht abgeschlossen
Game.UpdateInProgress=Ein Spielupdate läuft bereits.
Game.UpdateDialogTitle=War Thunder aktualisieren
Game.UpdateButton=SPIEL AKTUALISIEREN
Game.InstallationNotFound=War-Thunder-Installation nicht gefunden.
Game.UpdateInfo={0}  •  Installiert {1}  •  Server {2}
Game.UpdateVersionVerifyFailed=Die Version des gewählten Servers konnte nicht geprüft werden. Prüfe die Verbindung und versuche es erneut.
Game.UpdateAlreadyInstalled=Die Version des gewählten Servers ist bereits installiert.
Game.UpdateOfficialLauncher=Aktualisierung über den offiziellen Launcher. Er wird nach Abschluss automatisch geschlossen.
Game.UpdateComplete=Update abgeschlossen: {0}.
Game.UpdateUnconfirmed=Der Launcher wurde geschlossen, aber die gewählte Version konnte noch nicht bestätigt werden.
Game.UpdateLauncherFailed=Das Update über den offiziellen Launcher wurde nicht abgeschlossen.
Warning.CloseLauncherBeforeServer=Schließe den War-Thunder-Launcher, bevor du den Live/Test-Server wechselst.
""",
        ["fr"] = """
Switch.SequenceTitle=Séquence d'actions
Switch.SequenceKey=Touche
Switch.SequencePressCount=Nombre de pressions (1–20)
Switch.SequenceDelay=Délai après pression (ms, 0–5000)
Switch.SequenceAddKey=Ajouter une touche
Switch.SequenceRemove=Supprimer
Switch.SequenceMoveUp=Monter
Switch.SequenceMoveDown=Descendre
Switch.SequenceCaptureKey=Capturer la touche
Switch.SequenceValidation=Choisissez une touche, 1–20 pressions et un intervalle de 0–5000 ms pour chaque ligne.
Switch.GestureTitle=Enregistrer un geste avancé
Switch.GestureRecord=Enregistrer
Switch.GestureStop=Arrêter
Switch.GestureUse=Utiliser le geste
Switch.GestureDisconnected=Périphérique déconnecté. Recommencez l'enregistrement.
Switch.GestureLine={0} ms | boutons 0x{1:X8}
Switch.SequenceKeyboardOnly=Cette ligne utilise une séquence clavier. Ajoutez une ligne souris séparée.
Switch.GestureNeedsSequence=Attribuez une séquence d'actions au geste enregistré avant d'enregistrer.
Switch.LegacyFlapsRemoved=L'ancienne logique automatique des volets a été supprimée. Configurez une séquence d'actions normale, puis activez l'interrupteur.
Switch.VJoyOutputTitle=Sortie vJoy
Game.VerifyBranchFailed=WT Assistant n'a pas pu vérifier le build {0} requis auprès de Gaijin.\n\nLe jeu ne sera pas lancé sur une branche non vérifiée. Vérifiez votre connexion et réessayez.
Game.VersionCheckTitle=Vérification de la version de War Thunder
Game.BranchUpdateIncomplete=Le lanceur officiel s'est terminé, mais le build installé ({0}) ne correspond toujours pas exactement au build {1} sélectionné ({2}).\n\nWT Assistant ne lancera pas la mauvaise branche.
Game.BranchUpdateTitle=Mise à jour de branche incomplète
Game.UpdateInProgress=Une mise à jour du jeu est déjà en cours.
Game.UpdateDialogTitle=Mettre à jour War Thunder
Game.UpdateButton=METTRE À JOUR LE JEU
Game.InstallationNotFound=Installation de War Thunder introuvable.
Game.UpdateInfo={0}  •  Installée {1}  •  Serveur {2}
Game.UpdateVersionVerifyFailed=Impossible de vérifier la version du serveur sélectionné. Vérifiez la connexion et réessayez.
Game.UpdateAlreadyInstalled=La version du serveur sélectionné est déjà installée.
Game.UpdateOfficialLauncher=Mise à jour via le lanceur officiel. Il se fermera automatiquement à la fin.
Game.UpdateComplete=Mise à jour terminée : {0}.
Game.UpdateUnconfirmed=Le lanceur s'est fermé, mais la version sélectionnée n'a pas encore pu être confirmée.
Game.UpdateLauncherFailed=La mise à jour via le lanceur officiel ne s'est pas terminée.
Warning.CloseLauncherBeforeServer=Fermez le lanceur War Thunder avant de changer de serveur Live/Test.
""",
        ["pt"] = """
Switch.SequenceTitle=Sequência de ações
Switch.SequenceKey=Tecla
Switch.SequencePressCount=Número de pressões (1–20)
Switch.SequenceDelay=Atraso após pressionar (ms, 0–5000)
Switch.SequenceAddKey=Adicionar tecla
Switch.SequenceRemove=Remover
Switch.SequenceMoveUp=Mover para cima
Switch.SequenceMoveDown=Mover para baixo
Switch.SequenceCaptureKey=Capturar tecla
Switch.SequenceValidation=Escolha uma tecla, 1–20 pressões e um intervalo de 0–5000 ms para cada linha.
Switch.GestureTitle=Gravar gesto avançado
Switch.GestureRecord=Gravar
Switch.GestureStop=Parar
Switch.GestureUse=Usar gesto
Switch.GestureDisconnected=Dispositivo desligado. Grave novamente.
Switch.GestureLine={0} ms | botões 0x{1:X8}
Switch.SequenceKeyboardOnly=Esta linha usa uma sequência de teclado. Adicione uma linha separada para o rato.
Switch.GestureNeedsSequence=Atribua uma sequência de ações ao gesto gravado antes de guardar.
Switch.LegacyFlapsRemoved=A antiga lógica automática de flaps foi removida. Configure uma sequência de ações normal e ative o interruptor.
Switch.VJoyOutputTitle=Saída vJoy
Game.VerifyBranchFailed=WT Assistant não conseguiu verificar a build {0} necessária da Gaijin.\n\nO jogo não será iniciado num branch não verificado. Verifique a ligação e tente novamente.
Game.VersionCheckTitle=Verificação da versão do War Thunder
Game.BranchUpdateIncomplete=O launcher oficial terminou, mas a build instalada ({0}) ainda não corresponde exatamente à build {1} selecionada ({2}).\n\nWT Assistant não iniciará o branch errado.
Game.BranchUpdateTitle=Atualização do branch incompleta
Game.UpdateInProgress=Já existe uma atualização do jogo em curso.
Game.UpdateDialogTitle=Atualizar War Thunder
Game.UpdateButton=ATUALIZAR JOGO
Game.InstallationNotFound=Instalação do War Thunder não encontrada.
Game.UpdateInfo={0}  •  Instalada {1}  •  Servidor {2}
Game.UpdateVersionVerifyFailed=Não foi possível verificar a versão do servidor selecionado. Verifique a ligação e tente novamente.
Game.UpdateAlreadyInstalled=A versão do servidor selecionado já está instalada.
Game.UpdateOfficialLauncher=A atualizar através do launcher oficial. Será fechado automaticamente quando terminar.
Game.UpdateComplete=Atualização concluída: {0}.
Game.UpdateUnconfirmed=O launcher fechou, mas a versão selecionada ainda não pôde ser confirmada.
Game.UpdateLauncherFailed=A atualização através do launcher oficial não foi concluída.
Warning.CloseLauncherBeforeServer=Feche o launcher do War Thunder antes de mudar o servidor Live/Test.
""",
        ["pl"] = """
Switch.SequenceTitle=Sekwencja akcji
Switch.SequenceKey=Klawisz
Switch.SequencePressCount=Liczba naciśnięć (1–20)
Switch.SequenceDelay=Opóźnienie po naciśnięciu (ms, 0–5000)
Switch.SequenceAddKey=Dodaj klawisz
Switch.SequenceRemove=Usuń
Switch.SequenceMoveUp=Przenieś w górę
Switch.SequenceMoveDown=Przenieś w dół
Switch.SequenceCaptureKey=Przechwyć klawisz
Switch.SequenceValidation=Wybierz klawisz, 1–20 naciśnięć i odstęp 0–5000 ms dla każdego wiersza.
Switch.GestureTitle=Nagraj zaawansowany gest
Switch.GestureRecord=Nagraj
Switch.GestureStop=Zatrzymaj
Switch.GestureUse=Użyj gestu
Switch.GestureDisconnected=Urządzenie odłączone. Nagraj ponownie.
Switch.GestureLine={0} ms | przyciski 0x{1:X8}
Switch.SequenceKeyboardOnly=Ten wiersz używa sekwencji klawiatury. Dodaj osobny wiersz myszy.
Switch.GestureNeedsSequence=Przed zapisaniem przypisz sekwencję akcji do nagranego gestu.
Switch.LegacyFlapsRemoved=Stara automatyczna logika klap została usunięta. Skonfiguruj zwykłą sekwencję akcji, a następnie włącz przełącznik.
Switch.VJoyOutputTitle=Wyjście vJoy
Game.VerifyBranchFailed=WT Assistant nie mógł zweryfikować wymaganej kompilacji {0} od Gaijin.\n\nGra nie uruchomi się na niezweryfikowanej gałęzi. Sprawdź połączenie i spróbuj ponownie.
Game.VersionCheckTitle=Sprawdzanie wersji War Thunder
Game.BranchUpdateIncomplete=Oficjalny launcher zakończył pracę, ale zainstalowana kompilacja ({0}) nadal nie odpowiada dokładnie wybranej kompilacji {1} ({2}).\n\nWT Assistant nie uruchomi niewłaściwej gałęzi.
Game.BranchUpdateTitle=Aktualizacja gałęzi nieukończona
Game.UpdateInProgress=Aktualizacja gry jest już w toku.
Game.UpdateDialogTitle=Aktualizuj War Thunder
Game.UpdateButton=AKTUALIZUJ GRĘ
Game.InstallationNotFound=Nie znaleziono instalacji War Thunder.
Game.UpdateInfo={0}  •  Zainstalowana {1}  •  Serwer {2}
Game.UpdateVersionVerifyFailed=Nie udało się zweryfikować wersji wybranego serwera. Sprawdź połączenie i spróbuj ponownie.
Game.UpdateAlreadyInstalled=Wersja wybranego serwera jest już zainstalowana.
Game.UpdateOfficialLauncher=Aktualizacja przez oficjalny launcher. Zamknie się automatycznie po zakończeniu.
Game.UpdateComplete=Aktualizacja ukończona: {0}.
Game.UpdateUnconfirmed=Launcher został zamknięty, ale wybranej wersji nie udało się jeszcze potwierdzić.
Game.UpdateLauncherFailed=Aktualizacja przez oficjalny launcher nie została ukończona.
Warning.CloseLauncherBeforeServer=Zamknij launcher War Thunder przed zmianą serwera Live/Test.
""",
        ["ru"] = """
Switch.SequenceTitle=Последовательность действий
Switch.SequenceKey=Клавиша
Switch.SequencePressCount=Количество нажатий (1–20)
Switch.SequenceDelay=Задержка после нажатия (мс, 0–5000)
Switch.SequenceAddKey=Добавить клавишу
Switch.SequenceRemove=Удалить
Switch.SequenceMoveUp=Переместить вверх
Switch.SequenceMoveDown=Переместить вниз
Switch.SequenceCaptureKey=Захватить клавишу
Switch.SequenceValidation=Для каждой строки выберите клавишу, 1–20 нажатий и интервал 0–5000 мс.
Switch.GestureTitle=Запись расширенного жеста
Switch.GestureRecord=Запись
Switch.GestureStop=Стоп
Switch.GestureUse=Использовать жест
Switch.GestureDisconnected=Устройство отключено. Запишите снова.
Switch.GestureLine={0} мс | кнопки 0x{1:X8}
Switch.SequenceKeyboardOnly=Эта строка использует клавиатурную последовательность. Добавьте отдельную строку для мыши.
Switch.GestureNeedsSequence=Перед сохранением назначьте записанному жесту последовательность действий.
Switch.LegacyFlapsRemoved=Старая автоматическая логика закрылков удалена. Настройте обычную последовательность действий и включите переключатель.
Switch.VJoyOutputTitle=Выход vJoy
Game.VerifyBranchFailed=WT Assistant не смог проверить требуемую сборку {0} от Gaijin.\n\nИгра не будет запущена на непроверенной ветке. Проверьте подключение и повторите попытку.
Game.VersionCheckTitle=Проверка версии War Thunder
Game.BranchUpdateIncomplete=Официальный launcher завершил работу, но установленная сборка ({0}) всё ещё не совпадает с выбранной сборкой {1} ({2}).\n\nWT Assistant не запустит неверную ветку.
Game.BranchUpdateTitle=Обновление ветки не завершено
Game.UpdateInProgress=Обновление игры уже выполняется.
Game.UpdateDialogTitle=Обновление War Thunder
Game.UpdateButton=ОБНОВИТЬ ИГРУ
Game.InstallationNotFound=Установка War Thunder не найдена.
Game.UpdateInfo={0}  •  Установлена {1}  •  Сервер {2}
Game.UpdateVersionVerifyFailed=Не удалось проверить версию выбранного сервера. Проверьте подключение и повторите попытку.
Game.UpdateAlreadyInstalled=Версия выбранного сервера уже установлена.
Game.UpdateOfficialLauncher=Обновление через официальный launcher. Он автоматически закроется после завершения.
Game.UpdateComplete=Обновление завершено: {0}.
Game.UpdateUnconfirmed=Launcher закрылся, но выбранную версию пока не удалось подтвердить.
Game.UpdateLauncherFailed=Обновление через официальный launcher не завершилось.
Warning.CloseLauncherBeforeServer=Закройте launcher War Thunder перед сменой сервера Live/Test.
""",
        ["uk"] = """
Switch.SequenceTitle=Послідовність дій
Switch.SequenceKey=Клавіша
Switch.SequencePressCount=Кількість натискань (1–20)
Switch.SequenceDelay=Затримка після натискання (мс, 0–5000)
Switch.SequenceAddKey=Додати клавішу
Switch.SequenceRemove=Видалити
Switch.SequenceMoveUp=Перемістити вгору
Switch.SequenceMoveDown=Перемістити вниз
Switch.SequenceCaptureKey=Захопити клавішу
Switch.SequenceValidation=Для кожного рядка виберіть клавішу, 1–20 натискань та інтервал 0–5000 мс.
Switch.GestureTitle=Запис розширеного жесту
Switch.GestureRecord=Запис
Switch.GestureStop=Стоп
Switch.GestureUse=Використати жест
Switch.GestureDisconnected=Пристрій відключено. Запишіть знову.
Switch.GestureLine={0} мс | кнопки 0x{1:X8}
Switch.SequenceKeyboardOnly=Цей рядок використовує клавіатурну послідовність. Додайте окремий рядок для миші.
Switch.GestureNeedsSequence=Перед збереженням призначте записаному жесту послідовність дій.
Switch.LegacyFlapsRemoved=Стару автоматичну логіку закрилків видалено. Налаштуйте звичайну послідовність дій і ввімкніть перемикач.
Switch.VJoyOutputTitle=Вихід vJoy
Game.VerifyBranchFailed=WT Assistant не зміг перевірити потрібну збірку {0} від Gaijin.\n\nГра не запускатиметься на неперевіреній гілці. Перевірте з'єднання й повторіть спробу.
Game.VersionCheckTitle=Перевірка версії War Thunder
Game.BranchUpdateIncomplete=Офіційний launcher завершив роботу, але встановлена збірка ({0}) усе ще не відповідає вибраній збірці {1} ({2}).\n\nWT Assistant не запустить неправильну гілку.
Game.BranchUpdateTitle=Оновлення гілки не завершено
Game.UpdateInProgress=Оновлення гри вже виконується.
Game.UpdateDialogTitle=Оновити War Thunder
Game.UpdateButton=ОНОВИТИ ГРУ
Game.InstallationNotFound=Інсталяцію War Thunder не знайдено.
Game.UpdateInfo={0}  •  Встановлена {1}  •  Сервер {2}
Game.UpdateVersionVerifyFailed=Не вдалося перевірити версію вибраного сервера. Перевірте з'єднання й повторіть спробу.
Game.UpdateAlreadyInstalled=Версію вибраного сервера вже встановлено.
Game.UpdateOfficialLauncher=Оновлення через офіційний launcher. Він автоматично закриється після завершення.
Game.UpdateComplete=Оновлення завершено: {0}.
Game.UpdateUnconfirmed=Launcher закрився, але вибрану версію поки не вдалося підтвердити.
Game.UpdateLauncherFailed=Оновлення через офіційний launcher не завершилося.
Warning.CloseLauncherBeforeServer=Закрийте launcher War Thunder перед зміною сервера Live/Test.
""",
        ["tr"] = """
Switch.SequenceTitle=Eylem sırası
Switch.SequenceKey=Tuş
Switch.SequencePressCount=Basma sayısı (1–20)
Switch.SequenceDelay=Basma sonrası gecikme (ms, 0–5000)
Switch.SequenceAddKey=Tuş ekle
Switch.SequenceRemove=Kaldır
Switch.SequenceMoveUp=Yukarı taşı
Switch.SequenceMoveDown=Aşağı taşı
Switch.SequenceCaptureKey=Tuşu yakala
Switch.SequenceValidation=Her satır için bir tuş, 1–20 basma ve 0–5000 ms aralık seçin.
Switch.GestureTitle=Gelişmiş hareket kaydet
Switch.GestureRecord=Kaydet
Switch.GestureStop=Durdur
Switch.GestureUse=Hareketi kullan
Switch.GestureDisconnected=Cihaz bağlantısı kesildi. Yeniden kaydedin.
Switch.GestureLine={0} ms | düğmeler 0x{1:X8}
Switch.SequenceKeyboardOnly=Bu satır klavye sırası kullanıyor. Ayrı bir fare satırı ekleyin.
Switch.GestureNeedsSequence=Kaydetmeden önce kaydedilen harekete bir Eylem Sırası atayın.
Switch.LegacyFlapsRemoved=Eski otomatik flap mantığı kaldırıldı. Normal bir eylem sırası yapılandırın ve anahtarı etkinleştirin.
Switch.VJoyOutputTitle=vJoy çıkışı
Game.VerifyBranchFailed=WT Assistant, Gaijin'den gerekli {0} yapısını doğrulayamadı.\n\nOyun doğrulanmamış bir dalda başlatılmayacak. İnternet bağlantınızı kontrol edip tekrar deneyin.
Game.VersionCheckTitle=War Thunder sürüm kontrolü
Game.BranchUpdateIncomplete=Resmî launcher tamamlandı ancak kurulu yapı ({0}) seçilen {1} yapısıyla ({2}) hâlâ tam eşleşmiyor.\n\nWT Assistant yanlış dalı başlatmayacak.
Game.BranchUpdateTitle=Dal güncellemesi tamamlanmadı
Game.UpdateInProgress=Bir oyun güncellemesi zaten devam ediyor.
Game.UpdateDialogTitle=War Thunder'ı Güncelle
Game.UpdateButton=OYUNU GÜNCELLE
Game.InstallationNotFound=War Thunder kurulumu bulunamadı.
Game.UpdateInfo={0}  •  Kurulu {1}  •  Sunucu {2}
Game.UpdateVersionVerifyFailed=Seçilen sunucu sürümü doğrulanamadı. Bağlantınızı kontrol edip tekrar deneyin.
Game.UpdateAlreadyInstalled=Seçilen sunucu sürümü zaten kurulu.
Game.UpdateOfficialLauncher=Resmî launcher üzerinden güncelleniyor. Güncelleme bitince otomatik kapanacak.
Game.UpdateComplete=Güncelleme tamamlandı: {0}.
Game.UpdateUnconfirmed=Launcher kapandı ancak seçilen sürüm henüz doğrulanamadı.
Game.UpdateLauncherFailed=Resmî launcher güncellemesi tamamlanmadı.
Warning.CloseLauncherBeforeServer=Live/Test sunucusunu değiştirmeden önce War Thunder launcher'ı kapatın.
""",
        ["el"] = """
Switch.SequenceTitle=Ακολουθία ενεργειών
Switch.SequenceKey=Πλήκτρο
Switch.SequencePressCount=Αριθμός πατημάτων (1–20)
Switch.SequenceDelay=Καθυστέρηση μετά το πάτημα (ms, 0–5000)
Switch.SequenceAddKey=Προσθήκη πλήκτρου
Switch.SequenceRemove=Αφαίρεση
Switch.SequenceMoveUp=Μετακίνηση πάνω
Switch.SequenceMoveDown=Μετακίνηση κάτω
Switch.SequenceCaptureKey=Καταγραφή πλήκτρου
Switch.SequenceValidation=Επιλέξτε πλήκτρο, 1–20 πατήματα και διάστημα 0–5000 ms για κάθε γραμμή.
Switch.GestureTitle=Καταγραφή σύνθετης κίνησης
Switch.GestureRecord=Καταγραφή
Switch.GestureStop=Διακοπή
Switch.GestureUse=Χρήση κίνησης
Switch.GestureDisconnected=Η συσκευή αποσυνδέθηκε. Καταγράψτε ξανά.
Switch.GestureLine={0} ms | κουμπιά 0x{1:X8}
Switch.SequenceKeyboardOnly=Αυτή η γραμμή χρησιμοποιεί ακολουθία πληκτρολογίου. Προσθέστε ξεχωριστή γραμμή ποντικιού.
Switch.GestureNeedsSequence=Αντιστοιχίστε ακολουθία ενεργειών στην καταγεγραμμένη κίνηση πριν την αποθήκευση.
Switch.LegacyFlapsRemoved=Η παλιά αυτόματη λογική flaps αφαιρέθηκε. Ρυθμίστε μια κανονική ακολουθία ενεργειών και ενεργοποιήστε τον διακόπτη.
Switch.VJoyOutputTitle=Έξοδος vJoy
Game.VerifyBranchFailed=Το WT Assistant δεν μπόρεσε να επαληθεύσει το απαιτούμενο build {0} από τη Gaijin.\n\nΤο παιχνίδι δεν θα ξεκινήσει σε μη επαληθευμένο branch. Ελέγξτε τη σύνδεση και δοκιμάστε ξανά.
Game.VersionCheckTitle=Έλεγχος έκδοσης War Thunder
Game.BranchUpdateIncomplete=Ο επίσημος launcher ολοκληρώθηκε, αλλά το εγκατεστημένο build ({0}) δεν ταιριάζει ακόμη ακριβώς με το επιλεγμένο {1} build ({2}).\n\nΤο WT Assistant δεν θα ξεκινήσει το λάθος branch.
Game.BranchUpdateTitle=Η ενημέρωση branch δεν ολοκληρώθηκε
Game.UpdateInProgress=Μια ενημέρωση παιχνιδιού βρίσκεται ήδη σε εξέλιξη.
Game.UpdateDialogTitle=Ενημέρωση War Thunder
Game.UpdateButton=ΕΝΗΜΕΡΩΣΗ ΠΑΙΧΝΙΔΙΟΥ
Game.InstallationNotFound=Η εγκατάσταση του War Thunder δεν βρέθηκε.
Game.UpdateInfo={0}  •  Εγκατεστημένη {1}  •  Server {2}
Game.UpdateVersionVerifyFailed=Δεν ήταν δυνατή η επαλήθευση της έκδοσης του επιλεγμένου server. Ελέγξτε τη σύνδεση και δοκιμάστε ξανά.
Game.UpdateAlreadyInstalled=Η έκδοση του επιλεγμένου server είναι ήδη εγκατεστημένη.
Game.UpdateOfficialLauncher=Ενημέρωση μέσω του επίσημου launcher. Θα κλείσει αυτόματα όταν ολοκληρωθεί.
Game.UpdateComplete=Η ενημέρωση ολοκληρώθηκε: {0}.
Game.UpdateUnconfirmed=Ο launcher έκλεισε, αλλά η επιλεγμένη έκδοση δεν έχει ακόμη επιβεβαιωθεί.
Game.UpdateLauncherFailed=Η ενημέρωση μέσω του επίσημου launcher δεν ολοκληρώθηκε.
Warning.CloseLauncherBeforeServer=Κλείστε τον launcher του War Thunder πριν αλλάξετε server Live/Test.
""",
        ["ro"] = """
Switch.SequenceTitle=Secvență de acțiuni
Switch.SequenceKey=Tastă
Switch.SequencePressCount=Număr de apăsări (1–20)
Switch.SequenceDelay=Întârziere după apăsare (ms, 0–5000)
Switch.SequenceAddKey=Adaugă tastă
Switch.SequenceRemove=Elimină
Switch.SequenceMoveUp=Mută în sus
Switch.SequenceMoveDown=Mută în jos
Switch.SequenceCaptureKey=Capturează tasta
Switch.SequenceValidation=Alege o tastă, 1–20 apăsări și un interval de 0–5000 ms pentru fiecare rând.
Switch.GestureTitle=Înregistrează gest avansat
Switch.GestureRecord=Înregistrează
Switch.GestureStop=Oprește
Switch.GestureUse=Folosește gestul
Switch.GestureDisconnected=Dispozitiv deconectat. Înregistrează din nou.
Switch.GestureLine={0} ms | butoane 0x{1:X8}
Switch.SequenceKeyboardOnly=Acest rând folosește o secvență de tastatură. Adaugă un rând separat pentru mouse.
Switch.GestureNeedsSequence=Atribuie o secvență de acțiuni gestului înregistrat înainte de salvare.
Switch.LegacyFlapsRemoved=Vechea logică automată pentru flaps a fost eliminată. Configurează o secvență normală de acțiuni, apoi activează comutatorul.
Switch.VJoyOutputTitle=Ieșire vJoy
Game.VerifyBranchFailed=WT Assistant nu a putut verifica build-ul {0} necesar de la Gaijin.\n\nJocul nu va porni pe un branch neverificat. Verifică conexiunea și încearcă din nou.
Game.VersionCheckTitle=Verificare versiune War Thunder
Game.BranchUpdateIncomplete=Launcher-ul oficial s-a încheiat, dar build-ul instalat ({0}) încă nu corespunde exact build-ului {1} selectat ({2}).\n\nWT Assistant nu va porni branch-ul greșit.
Game.BranchUpdateTitle=Actualizarea branch-ului nu este completă
Game.UpdateInProgress=O actualizare a jocului este deja în desfășurare.
Game.UpdateDialogTitle=Actualizează War Thunder
Game.UpdateButton=ACTUALIZEAZĂ JOCUL
Game.InstallationNotFound=Instalarea War Thunder nu a fost găsită.
Game.UpdateInfo={0}  •  Instalată {1}  •  Server {2}
Game.UpdateVersionVerifyFailed=Versiunea serverului selectat nu a putut fi verificată. Verifică conexiunea și încearcă din nou.
Game.UpdateAlreadyInstalled=Versiunea serverului selectat este deja instalată.
Game.UpdateOfficialLauncher=Actualizare prin launcher-ul oficial. Se va închide automat la final.
Game.UpdateComplete=Actualizare finalizată: {0}.
Game.UpdateUnconfirmed=Launcher-ul s-a închis, dar versiunea selectată nu a putut fi încă confirmată.
Game.UpdateLauncherFailed=Actualizarea prin launcher-ul oficial nu s-a finalizat.
Warning.CloseLauncherBeforeServer=Închide launcher-ul War Thunder înainte de a schimba serverul Live/Test.
""",
        ["he"] = """
Switch.SequenceTitle=רצף פעולות
Switch.SequenceKey=מקש
Switch.SequencePressCount=מספר לחיצות (1–20)
Switch.SequenceDelay=השהיה לאחר לחיצה (ms, 0–5000)
Switch.SequenceAddKey=הוסף מקש
Switch.SequenceRemove=הסר
Switch.SequenceMoveUp=העבר למעלה
Switch.SequenceMoveDown=העבר למטה
Switch.SequenceCaptureKey=קלוט מקש
Switch.SequenceValidation=בחר מקש, 1–20 לחיצות ומרווח של 0–5000 ms לכל שורה.
Switch.GestureTitle=הקלטת מחווה מתקדמת
Switch.GestureRecord=הקלט
Switch.GestureStop=עצור
Switch.GestureUse=השתמש במחווה
Switch.GestureDisconnected=ההתקן נותק. הקלט שוב.
Switch.GestureLine={0} ms | כפתורים 0x{1:X8}
Switch.SequenceKeyboardOnly=שורה זו משתמשת ברצף מקלדת. הוסף שורת עכבר נפרדת.
Switch.GestureNeedsSequence=הקצה רצף פעולות למחווה שהוקלטה לפני השמירה.
Switch.LegacyFlapsRemoved=לוגיקת ה-flaps האוטומטית הישנה הוסרה. הגדר רצף פעולות רגיל ולאחר מכן הפעל את המתג.
Switch.VJoyOutputTitle=פלט vJoy
Game.VerifyBranchFailed=WT Assistant לא הצליח לאמת את build {0} הנדרש מ-Gaijin.\n\nהמשחק לא יופעל על branch שלא אומת. בדוק את החיבור ונסה שוב.
Game.VersionCheckTitle=בדיקת גרסת War Thunder
Game.BranchUpdateIncomplete=ה-launcher הרשמי הסתיים, אך ה-build המותקן ({0}) עדיין אינו תואם בדיוק ל-build {1} שנבחר ({2}).\n\nWT Assistant לא יפעיל branch שגוי.
Game.BranchUpdateTitle=עדכון branch לא הושלם
Game.UpdateInProgress=עדכון משחק כבר מתבצע.
Game.UpdateDialogTitle=עדכון War Thunder
Game.UpdateButton=עדכן משחק
Game.InstallationNotFound=התקנת War Thunder לא נמצאה.
Game.UpdateInfo={0}  •  מותקן {1}  •  שרת {2}
Game.UpdateVersionVerifyFailed=לא ניתן לאמת את גרסת השרת שנבחר. בדוק את החיבור ונסה שוב.
Game.UpdateAlreadyInstalled=גרסת השרת שנבחר כבר מותקנת.
Game.UpdateOfficialLauncher=מתעדכן דרך ה-launcher הרשמי. הוא ייסגר אוטומטית עם סיום העדכון.
Game.UpdateComplete=העדכון הושלם: {0}.
Game.UpdateUnconfirmed=ה-launcher נסגר, אך עדיין לא ניתן לאשר את הגרסה שנבחרה.
Game.UpdateLauncherFailed=העדכון דרך ה-launcher הרשמי לא הושלם.
Warning.CloseLauncherBeforeServer=סגור את ה-launcher של War Thunder לפני החלפת שרת Live/Test.
""",
        ["zh-Hans"] = """
Switch.SequenceTitle=动作序列
Switch.SequenceKey=按键
Switch.SequencePressCount=按键次数（1–20）
Switch.SequenceDelay=按下后的延迟（ms，0–5000）
Switch.SequenceAddKey=添加按键
Switch.SequenceRemove=移除
Switch.SequenceMoveUp=上移
Switch.SequenceMoveDown=下移
Switch.SequenceCaptureKey=捕获按键
Switch.SequenceValidation=请为每一行选择一个按键、1–20 次按下以及 0–5000 ms 的间隔。
Switch.GestureTitle=记录高级手势
Switch.GestureRecord=记录
Switch.GestureStop=停止
Switch.GestureUse=使用手势
Switch.GestureDisconnected=设备已断开。请重新记录。
Switch.GestureLine={0} ms | 按钮 0x{1:X8}
Switch.SequenceKeyboardOnly=此行使用键盘序列。请单独添加一个鼠标行。
Switch.GestureNeedsSequence=保存前，请为记录的手势分配动作序列。
Switch.LegacyFlapsRemoved=旧的自动襟翼逻辑已移除。请配置普通动作序列，然后启用该开关。
Switch.VJoyOutputTitle=vJoy 输出
Game.VerifyBranchFailed=WT Assistant 无法从 Gaijin 验证所需的 {0} 版本。\n\n游戏不会在未验证的分支上启动。请检查网络连接后重试。
Game.VersionCheckTitle=War Thunder 版本检查
Game.BranchUpdateIncomplete=官方启动器已结束，但已安装版本（{0}）仍与所选 {1} 版本（{2}）不完全一致。\n\nWT Assistant 不会启动错误的分支。
Game.BranchUpdateTitle=分支更新未完成
Game.UpdateInProgress=游戏更新已在进行中。
Game.UpdateDialogTitle=更新 War Thunder
Game.UpdateButton=更新游戏
Game.InstallationNotFound=未找到 War Thunder 安装目录。
Game.UpdateInfo={0}  •  已安装 {1}  •  服务器 {2}
Game.UpdateVersionVerifyFailed=无法验证所选服务器版本。请检查网络连接后重试。
Game.UpdateAlreadyInstalled=所选服务器版本已安装。
Game.UpdateOfficialLauncher=正在通过官方启动器更新。更新完成后会自动关闭。
Game.UpdateComplete=更新完成：{0}。
Game.UpdateUnconfirmed=启动器已关闭，但暂时无法确认所选版本。
Game.UpdateLauncherFailed=官方启动器更新未完成。
Warning.CloseLauncherBeforeServer=更改 Live/Test 服务器前，请关闭 War Thunder 启动器。
""",
    };
}
